server:
  port: 8081
app:
  test: 123
  scheduler:
    interval: 15000
springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
spring:
  datasource:
    url:
      jdbc:postgresql://postgresql:5432/scrapper