server:
  port: 8080
app:
  test: 1235
  token: "5788332133:AAEqYLhlrpi77tRYxKiND9aNhOHCjL6geMA"
springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui